# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod tidy
builds:
- id: pair
  binary: pair
  env:
  - CGO_ENABLED=0
  main: ./cmd/pair/main.go
  goos:
  - darwin
  - linux
  goarch:
  - amd64
- id: pair-server
  binary: pair-server
  env:
  - CGO_ENABLED=0
  main: ./cmd/pair-server/main.go
  goos:
  - darwin
  - linux
  goarch:
  - amd64
- id: pair-server-simple
  binary: pair-server-simple
  env:
  - CGO_ENABLED=0
  main: ./cmd/pair-server-simple/main.go
  goos:
  - darwin
  - linux
  goarch:
  - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
  files:
  - README.md
  - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
brews:
- name: pair
  tap:
    owner: bottlerocketlabs
    name: homebrew-apps
    token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
  folder: Formula
  homepage:  https://github.com/bottlerocketlabs/pair
  description: A tool for pair programming
  license: MIT
  test: |
    system "#{bin}/pair -version"
  dependencies:
  - name: go
  install: |-
    bin.install "pair"
    bin.install "pair-server"
    bin.install "pair-server-simple"